<script lang="ts">
  import { errorText } from '$lib/translations/labels';
  import { onDestroy } from 'svelte';
  import { listen, type UnlistenFn } from '@tauri-apps/api/event';
  import { getOrCreatePatientChatSession, runAgentTurn, type SubstanceDetail } from '$lib/api';
  import { t } from '$lib/translations';
  import { thinkingEffort } from '$lib/stores/thinking';
  import { get } from 'svelte/store';
  import { Alert, Button, ThinkingIndicator } from '$lib/components/ui';
  import { chatActivityStage } from '$lib/chat-activity';
  import MedicationComparisonPanel from './MedicationComparisonPanel.svelte';

  interface Props {
    patientId: string;
    currentSubstance: SubstanceDetail;
    replacementSubstance: SubstanceDetail;
  }

  let { patientId, currentSubstance, replacementSubstance }: Props = $props();

  let aiGuidance = $state('');
  let isGenerating = $state(false);
  let activityStartedAt = $state<number | null>(null);
  let error = $state<string | null>(null);
  let sessionId = $state<string | null>(null);

  // Track active listeners so they can be cleaned up on unmount.
  let activeUnlisteners: UnlistenFn[] = [];

  function cleanupListeners() {
    activeUnlisteners.forEach((fn) => fn());
    activeUnlisteners = [];
  }

  onDestroy(cleanupListeners);

  async function generateGuidance() {
    try {
      isGenerating = true;
      activityStartedAt = Date.now();
      error = null;
      aiGuidance = '';

      // Clean up any listeners from a previous run.
      cleanupListeners();

      // Create or get the chat session for this patient
      const session = await getOrCreatePatientChatSession(patientId);
      sessionId = session.id;

      // Set up event listeners for streaming
      const chunkUnlisten = await listen<string>('agent-chunk', (event) => {
        aiGuidance += event.payload;
      });

      const doneUnlisten = await listen<void>('agent-done', () => {
        isGenerating = false;
        activityStartedAt = null;
        cleanupListeners();
      });

      activeUnlisteners = [chunkUnlisten, doneUnlisten];

      // Construct a prompt that asks the agent to compare the medications
      const prompt = `Bitte vergleiche die folgenden beiden Medikamente und gib eine Entscheidungshilfe für den Medikamentenwechsel:

Aktuelles Medikament: ${currentSubstance.name_de} (ID: ${currentSubstance.id})
Neues Medikament: ${replacementSubstance.name_de} (ID: ${replacementSubstance.id})

Nutze das compare_medications Tool, um detaillierte Informationen zu beiden Medikamenten abzurufen, und erstelle dann eine Zusammenfassung mit folgenden Punkten:

1. Gemeinsamkeiten und Unterschiede in der Indikation
2. Vergleich der Nebenwirkungen (überlappend und unterschiedlich)
3. Kontraindikationen, die beachtet werden müssen
4. Empfehlung für den Medikamentenwechsel
5. Wichtige Punkte für das Monitoring nach dem Wechsel`;

      // Send the message to the agent
      await runAgentTurn(sessionId, prompt, get(thinkingEffort));
    } catch (err) {
      error = $errorText(err);
      isGenerating = false;
      activityStartedAt = null;
      cleanupListeners();
    }
  }
</script>

<div class="space-y-6">
  <!-- Comparison Panel -->
  <MedicationComparisonPanel current={currentSubstance} replacement={replacementSubstance} />

  <!-- Guidance Section -->
  <div class="bg-surface-raised border border-line rounded-card p-6">
    <div class="flex items-center justify-between mb-4">
      <h3 class="text-heading font-semibold text-fg">{$t('medications.decisionSupport')}</h3>
      <Button variant="primary" onclick={generateGuidance} loading={isGenerating}>
        {$t('medications.generateDecisionSupport')}
      </Button>
    </div>

    {#if error}
      <Alert tone="danger" class="mb-4">{error}</Alert>
    {/if}

    {#if aiGuidance || isGenerating}
      <div class="prose dark:prose-invert max-w-none">
        <p class="text-caption text-fg-subtle mb-2">{$t('common.autoGenerated')}</p>
        <div class="whitespace-pre-wrap text-body text-fg-muted bg-surface-sunken rounded-card p-4">
          {#if isGenerating && activityStartedAt}
            <div class={aiGuidance ? 'mb-2' : ''}>
              <ThinkingIndicator
                stage={chatActivityStage(aiGuidance)}
                startedAt={activityStartedAt}
                label={$t('medications.activityWriting')}
              />
            </div>
          {/if}
          {aiGuidance}
        </div>
      </div>
    {:else}
      <p class="text-body text-fg-muted">{$t('medications.decisionSupportHint')}</p>
    {/if}
  </div>
</div>
